baseURL: "https://cakewithdivinity.github.io/"
languageCode: "en-us"
title: "Hendrik Loewe | Webdeveloper"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: View my Blog posts
      url: /blogs
      weight: 1

params:
  title: "Hendrik Loewe"
  description: My personal Portfolio and Blog

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: true
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  color:

    darkmode:
      textColor: "#a3abd0"
      secondaryTextColor: "#a3abd0"
      backgroundColor: "#1a1b26"
      primaryColor: "#6280c3"
      secondaryColor: "#24283b"

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Hendrik Loewe."
    subtitle: "And I make Computers go Beep-Boop"
    content: "I am a young Web-Developer based in Wuppertal, Germany. I strive for correctness, clean code and performance."
    image: /images/portrait.jpg
    # button:
    #   enable: true
    #   name: "Resume"
    #   url: "/Resume-Hendrik-Loewe.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/CakeWithDivinity
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/hendrik-loewe-04ba2b202/
        - icon: fas fa-envelope
          url: mailto:hendrikloewe3@gmail.com

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am a Web-developer primarily working with Angular and Symfony. Right now I am studying Computer Science at the FOM-Hochschule in Düsseldorf.
      I enjoy reactive programming with RxJS and NGRX and am trying to do Test-Driven-Development as far as I can.
      At work I develop highly complex configurators for our customers, which let users configure products to their individual needs.
      In my freetime I like to learn more about coding and try to improve myself towards writing clean, correct and performant code.
    skills:
      enable: true
      title: "Here are a few technologies I've worked with before:"
      items:
        - "Angular"
        - "RxJS"
        - "NgRX"
        - "Karma"
        - "Cypress"
        - "Symfony"
        - "ApiPlatform"
        - "Git"
        
  # Experience
  experience:
    enable: true
    items:
      - job: "Software Engineering Trainee"
        company: "Web-Fabric GmbH Trainee"
        companyUrl: "https://www.web-fabric.de/"
        date: "Aug 2021 - present"
        content: |- 
          I am currently working as a software engineering trainee at [Web-Fabric GmbH](https://www.web-fabric.de/) in Wuppertal for 3 days a week, while I visit a University the rest of the week.
          At work, we develop complex configurators, shops and other customized solutions for our customers. In my first year I almost only
          worked in the frontend, implementing business logic for configurators in Angular using RxJS and NGRX. Then I did more and more stuff on the backend
          so that I could handle tasks more easily on my own as a Fullstack engineer.
          Personally, I want our customers to get the best product shipped, so I read a lot of Blog posts and books in my freetime and try
          to apply the newly gained knowledge in our new projects and by refactoring old ones.
      - job: "Software Engineering Intern"
        company: "Web-Fabric GmbH Intern"
        companyUrl: "https://www.web-fabric.de/"
        date: "Oct 2019 - Aug 2021"
        content: | 
          After a 2 week long internship, which he had to do in order to get our degree, I got a job offer from [Web-Fabric GmbH](https://www.web-fabric.de/).
          I convinced them of the knowledge in program, which I gained by doing software-engineering as a hobby since I was ten.
          In the first year I had a mentor on my side, supervising my rewrite of a Product in ASP.NET Core.
          While in the second year, I got to develop implementations of an internal framework as sample-applications, so other developers on our team
          could understand and use the library more easily. 

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "FOM University of Applied Sciences for Economics and Management"
          url: "https://www.fom.de/"
        date: "Sep 2021 - Mar 2025"
        GPA: "AVG until now: 1.2 out of 5 (1-5 lower is better)"
        content: |-
          - Scientific Papers:
            - Image Processing and Facial Recognition using Artificial Intelligence
            - Product-Specification-Sheet for the implementation of a Smart-Mirror
      - title: "University Entrance Diploma"
        school:
          name: "Carl-Fuhlrott-Gymnasium, Wuppertal"
          url: "http://cfg.wtal.de/"
        date: "Aug 2013 - Aug 2021"
        GPA: "832 out of 900"
        content: |-
          - A-Level Subjects:
            - Mathematics (Intensive Course)
            - Geography (Intensive Course)
            - Computer Science (Oral Basic Course)
            - English (Written Basic Course)
          - In 10th grade I worked on a scientific paper on how to secure a modern Web-Application
          - From 10th to 12th grade I regularly took part in an Astronomy course, where we worked with highly professional equipment to observe stars, nebulas and learn about our galaxy at the [Schülerlabor Astronomie](https://www.schuelerlabor-astronomie.de/)
          - I discovered a highly severe security vulnerability in our schools online system, revealing the passwords of students
          - I developed a Web-Application for a school project about the European Union
          - I volunteered as a event-technician for our school events, setting up Cameras, Lights and Audio for i.e. the Symphony-Orchestra Wuppertal

  # Achievements
  achievements:
    enable: true
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com