baseURL: "https://cakewithdivinity.github.io/"
languageCode: "en-us"
title: "Hendrik Loewe | Webdeveloper"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: View my Blog posts
      url: /blogs
      weight: 1

params:
  title: "Hendrik Loewe"
  description: My personal portfolio and blog

  useBootstrapCDN: false

  theme:
    disableThemeToggle: true

  color:

    darkmode:
      textColor: "#a3abd0"
      secondaryTextColor: "#a3abd0"
      backgroundColor: "#1a1b26"
      primaryColor: "#6280c3"
      secondaryColor: "#24283b"

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Hendrik Loewe."
    subtitle: "And I Make Computers Go Beep-Boop"
    content: "I am a young web-developer based in Wuppertal, Germany. I strive for correctness, clean code and performance."
    image: /images/portrait.jpg
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/CakeWithDivinity
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/hendrik-loewe-04ba2b202/
        - icon: fas fa-envelope
          url: mailto:hendrikloewe3@gmail.com

  # About
  about:
    enable: true
    title: "About Me"
    image: /images/portrait-with-cat.jpg
    content: |-
      I am a web-developer primarily working with Angular and Symfony. Right now I am studying computer-science at the FOM-Hochschule in Düsseldorf.
      I enjoy reactive programming with RxJS and NgRX and am trying to utilize test-driven-development as far as I can.
      At work, I develop highly complex configurators for our customers, which let users configure products to their individual needs.
      In my freetime I like to learn more about coding and try to improve myself towards writing clean, correct and performant code.
      Right now this includes learning Rust and tools for easier testing in Angular
    skills:
      enable: true
      title: "Here are a few technologies I've worked with before:"
      items:
        - "Angular"
        - "RxJS"
        - "NgRX"
        - "Karma"
        - "Cypress"
        - "Jest"
        - "Symfony"
        - "ApiPlatform"
        - "Git"
        
  # Experience
  experience:
    enable: true
    items:
      - job: "Software Engineering Trainee"
        company: "Web-Fabric GmbH Trainee"
        companyUrl: "https://www.web-fabric.de/"
        date: "Aug 2021 - present"
        content: |- 
          I am currently working as a software engineering trainee at [Web-Fabric GmbH](https://www.web-fabric.de/) in Wuppertal for 3 days a week, while I visit a university the rest of the week.
          At work, we develop complex configurators, shops and other custom solutions for our customers.
          My typical day at work contains the following activities:
            - Implementing new features in the front- or backend using our Techstack (Angular, Symfony and Postgres)
            - Reviewing Angular code of my coworkers and assissting them in writing performant and reactive code
            - Maintaining an internal framework to handle rendering and change-processing of forms with several hundred fields and options
            - Improving the Requirements-Engineering workflow at our company
      - job: "Software Engineering Intern"
        company: "Web-Fabric GmbH Intern"
        companyUrl: "https://www.web-fabric.de/"
        date: "Oct 2019 - Aug 2021"
        content: | 
          After a 2 week long internship, which we had to do in order to get our degree, I got a job offer from [Web-Fabric GmbH](https://www.web-fabric.de/).
          I convinced them of the knowledge in programming, which I gained by doing software-engineering as a hobby since I was ten years old.
          In the first year I had a mentor on my side, supervising my rewrite of an existing API in ASP.NET Core.
          While, in the second year, I got to develop implementations of an internal framework as sample-applications, so other developers on our team
          could understand and use the library more easily. 

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "FOM University of Applied Sciences for Economics and Management"
          url: "https://www.fom.de/"
        date: "Sep 2021 - Mar 2025"
        GPA: "AVG until now: 1.2 out of 5 (1 to 5, lower is better)"
        content: |-
          - Scientific Papers:
            - Image processing and facial recognition using artificial intelligence
            - Product-specifications-heet for the implementation of a smart-mirror
            - Advantages of a docker based infrastructure during the development and deployment of software 
      - title: "University Entrance Diploma"
        school:
          name: "Carl-Fuhlrott-Gymnasium, Wuppertal"
          url: "http://cfg.wtal.de/"
        date: "Aug 2013 - Aug 2021"
        GPA: "832 out of 900"
        content: |-
          - A-Level Subjects:
            - Mathematics (Intensive Course)
            - Geography (Intensive Course)
            - Computer Science (Oral Basic Course)
            - English (Written Basic Course)
          - In 10th grade I worked on a scientific paper on how to secure a modern web-application
          - From 10th to 12th grade I regularly took part in an astronomy course, where we worked with highly professional equipment to observe stars, nebulas and learn about our galaxy at the [Schülerlabor Astronomie](https://www.schuelerlabor-astronomie.de/)
          - I discovered a highly severe security vulnerability in our schools online system, revealing the passwords of students
          - I developed a web-application for a school project about the european union
          - I volunteered as an event-technician for our school events, setting up cameras, lights and audio for i.e. the Symfonie-Orchester Wuppertal

  #Contact
  contact:
    enable: true
    content: Feel free to shoot me a message via one of my socials or by mailing me
    email: hendrikloewe3@gmail.com
    btnName: Mail me

  footer:
    enable: false
    recentPosts: true
    socialNetworks:
      github: https://github.com/CakeWithDivinity
      linkedin: https://www.linkedin.com/in/hendrik-loewe-04ba2b202/
